# Generated by Django 3.0 on 2020-06-11 07:23

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_code', models.CharField(blank=True, editable=False, max_length=12)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='images/stores_icons')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='images/stores_banners')),
                ('drivers', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activated_by_user', to=settings.AUTH_USER_MODEL)),
                ('workers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
