# Generated by Django 3.0 on 2020-06-30 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_stock_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='drivers',
            new_name='address',
        ),
    ]
