# Generated by Django 3.0 on 2020-04-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0004_auto_20200424_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypoliciesandtermsofuse',
            name='_type',
            field=models.CharField(choices=[('terms_of_use', 'terms_of_use'), ('privacy_policy', 'privacy_policy')], max_length=50),
        ),
    ]
