# Generated by Django 3.0 on 2020-04-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0008_auto_20200424_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypoliciesandtermsofuse',
            name='language',
            field=models.CharField(choices=[('english', 'english'), ('rwandese', 'rwandese')], max_length=30),
        ),
    ]
