# Generated by Django 3.0 on 2020-05-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0019_auto_20200525_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypoliciesandtermsofuse',
            name='language',
            field=models.CharField(choices=[('english', 'english'), ('rwandese', 'rwandese')], max_length=30),
        ),
    ]
