# Generated by Django 3.0 on 2020-06-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0073_auto_20200611_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypoliciesandtermsofuse',
            name='language',
            field=models.CharField(choices=[('english', 'english'), ('rwandese', 'rwandese')], max_length=30),
        ),
    ]
