# Generated by Django 3.0 on 2020-06-11 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200611_1406'),
        ('product', '0004_auto_20200611_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreviewers',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
