# Generated by Django 3.0 on 2020-06-11 12:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_stock_name'),
        ('productCategory', '0004_productcategory_created_by'),
        ('product', '0005_auto_20200611_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_code', models.CharField(blank=True, editable=False, max_length=14)),
                ('title', models.CharField(default='', max_length=500)),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.TextField()),
                ('total_quantity_in_stock', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('price', models.IntegerField(null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('quantity_to_sell', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productCategory.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productCategory.ProductCategory')),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.DiscountOffer')),
                ('item_condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.ConditionItems')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='store.Stock')),
            ],
        ),
    ]
