# Generated by Django 3.0 on 2020-06-30 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_stock_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel_ad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('action_name', models.CharField(max_length=50)),
                ('action', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='store.Stock')),
            ],
        ),
    ]
