# Generated by Django 3.0 on 2020-06-30 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserCustom', '0076_auto_20200630_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryinfo',
            old_name='drivers',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='drivers',
            new_name='address',
        ),
    ]
